#!/usr/bin/env python


import socket
from SimpleXMLRPCServer import SimpleXMLRPCServer
from SimpleXMLRPCServer import SimpleXMLRPCRequestHandler


# TODO: Read in a config file.
# TODO: Clone or update the source repo.
# TODO: Build the website to deploy.
# TODO: Update the last-updated time.
# TODO: Return None if successful.
# TODO: Return useful messages on failure.

# TODO: Handle HTTP requests and XML-RPC requests simultaneously.
# TODO: Add p5js to the repository static files.
# TODO: Handle requests for last-updated time.
# TODO: Handle requests for the sketch page.

# TODO: Figure out why this doesn't work between machines.


class WallmountRequestHandler(SimpleXMLRPCRequestHandler):
    rpc_paths = ('/wallmount',)


class WallmountFunctions:

	def deploy_sketch(self, sketch_name):
		# TODO: Attempt to deploy the sketch.
		return 'If the server worked, we would have deployed \'%s\'.' % sketch_name


def main():
	server = SimpleXMLRPCServer((socket.gethostname(), 8000),
                            requestHandler=WallmountRequestHandler)
	server.register_instance(WallmountFunctions())
	print 'Starting XML-RPC server.'
	server.serve_forever()


if __name__ == '__main__':
	main()
